name: 🐛 Bug Report
description: Report an issue that should be fixed
labels: [bug]
body:
  - type: input
    attributes:
      label: What version of HonoX are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide a code snippet that can reproduce it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
  - type: textarea
    attributes:
      label: What do you see instead?
  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
