/** JSX */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type CreateElement<TElement = Node> = (type: any, props: any) => TElement | Promise<TElement>
export type CreateChildren<TElement = Node> = (
  childNodes: NodeListOf<ChildNode>
) => (string | TElement)[] | Promise<(string | TElement)[]>
export type HydrateComponent = (doc: {
  querySelectorAll: typeof document.querySelectorAll
}) => Promise<void>
export type TriggerHydration = (trigger: HydrateComponent) => void

/** Metadata generated by HonoX for one island root. */
type IslandRoot = Readonly<{
  /** Deterministic ID shared by the server and client renderers. */
  id: string
}>

/** Renderer-managed state used to distinguish root, nested, and prop-content islands. */
export type IslandState = Readonly<{
  inIsland: boolean
  inChildren: boolean
}>

/** Renderer-specific props applied to the generated `<honox-island>` element. */
export type ServerIslandRootProps = Record<string, unknown>

/** Server-side adapter used to construct and render island roots. */
export type ServerRenderer<TElement = unknown> = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  createElement: (type: any, props: any) => TElement
  isElement: (value: unknown) => boolean
  island: {
    useState: () => IslandState
    wrap: (createElement: () => TElement, state: IslandState) => TElement
  }
  renderRoot: (
    createRoot: () => TElement,
    createTemplates: () => TElement[],
    root: IslandRoot
  ) => ServerIslandRootProps | Promise<ServerIslandRootProps>
}

/** Client-side adapter used to reconstruct and hydrate island roots. */
export type ClientRenderer<TElement = unknown> = {
  createElement: CreateElement<TElement>
  hydrateRoot: (element: TElement, parent: HTMLElement, root: IslandRoot) => void | Promise<void>
  /** Optional support for reconstructing streamed Suspense content. */
  suspense?: {
    component: unknown
    suspend: <T>(promise: Promise<T>) => T
  }
}
